# Generated by Django 3.1.7 on 2021-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE Country( iso char(3) primary key ,name varchar(50) not null,	hdi float not null,	population biginteger not null,	start_vaccination_date date not null);"
        )
    ]
