# Generated by Django 3.1.7 on 2021-04-03 18:17

import os
from pathlib import Path
from django.db import migrations, models

from django.conf import settings
from django.conf.urls.static import static
from migrations_utils import get_sql_from_file

from migrations_utils import get_sql_from_ressources_files

class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(get_sql_from_file(os.path.join(settings.STATICFILES_DIRS[0], 'ressources/CSVtoSQL/fullfill_climate.sql')))],
            reverse_sql=[(get_sql_from_file(os.path.join(settings.STATICFILES_DIRS[0], 'ressources//CSVtoSQL/reverse_fill/reverse_fullfill_climate.sql')))]
        )
    ]
