# Generated by Django 3.1.7 on 2021-04-04 09:00

from django.db import migrations

from migrations_utils import get_sql_from_ressources_files

class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_insert_cleaned_climate'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(get_sql_from_ressources_files('CSVtoSQL/fullfill_cont.sql'))],
            reverse_sql=[(get_sql_from_ressources_files('CSVtoSQL/reverse_fill/reverse_fullfill_continent.sql'))]
        )
    ]
