# Generated by Django 3.1.7 on 2021-03-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20210324_0913'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("CREATE TABLE Climat( id SMALLSERIAL primary key, description varchar(100) not null unique);")],
            reverse_sql=[("DROP TABLE Climat")],

        )
    ]
