# Generated by Django 3.1.7 on 2021-03-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20210324_0939'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[("INSERT INTO Climat(description) VALUES ('Le Sahara sa mère')"),
            ("INSERT INTO Climat(description) VALUES ('Le climat méditéranéen')"),
            ("INSERT INTO Climat(description) VALUES ('Il neige comme en Russia')"),
            ("INSERT INTO Climat(description) VALUES ('Les pluies d acides ne semblent pas bonnes pour la santé')"),
            ("INSERT INTO Country VALUES ('BEL', 'Belgique', 80.9 , 20546, '2020-03-15')"),
            ("INSERT INTO Country VALUES ('FRA', 'France', 100.9 , 204461, '2020-03-14')"),
            ("INSERT INTO Country VALUES ('JPN', 'Japan', 100.78 , 66666, '2020-03-1')"),
            
            ],
            reverse_sql=[("DELETE FROM Climat WHERE description = 'Le Sahara sa mère'"),
            ("DELETE FROM Climat WHERE description = 'Le climat méditéranéen'"),
            ("DELETE FROM Climat WHERE description = 'Il neige comme en Russia'"),
            ("DELETE FROM Climat WHERE description = 'Les pluies d acides ne semblent pas bonnes pour la santé'"),
            ("DELETE FROM Country WHERE iso = 'BEL'"),
            ("DELETE FROM Country WHERE iso = 'FRA'"),
            ("DELETE FROM Country WHERE iso = 'FRA'"),

            ],
        )
    ]
