# Generated by Django 3.1.7 on 2021-04-04 09:01

from django.db import migrations

from migrations_utils import get_sql_from_ressources_files


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_insert_cleaned_continent'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[(get_sql_from_ressources_files('CSVtoSQL/fullfill_region.sql'))],
            reverse_sql=[(get_sql_from_ressources_files('CSVtoSQL/reverse_fill/reverse_fullfill_region.sql'))]
        )
    ]
