# Generated by Django 3.1.7 on 2021-05-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0012_auto_20210505_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('hdi', models.FloatField(verbose_name='HDI')),
                ('population', models.BigIntegerField()),
                ('surface', models.BigIntegerField()),
                ('start_vaccination_date', models.DateField()),
            ],
        ),
    ]
