INSERT INTO region VALUES($$ASIA (EX. NEAR EAST)$$,$$Asia$$);
INSERT INTO region VALUES($$SUB-SAHARAN AFRICA$$,$$Africa$$);
INSERT INTO region VALUES($$EASTERN EUROPE$$,$$Europe$$);
INSERT INTO region VALUES($$WESTERN EUROPE$$,$$Europe$$);
INSERT INTO region VALUES($$NEAR EAST$$,$$Asia$$);
INSERT INTO region VALUES($$LATIN AMER. & CARIB$$,$$South America$$);
INSERT INTO region VALUES($$C.W. OF IND. STATES$$,$$Asia$$);
INSERT INTO region VALUES($$OCEANIA$$,$$Oceania$$);
INSERT INTO region VALUES($$NORTHERN AMERICA$$,$$North America$$);
INSERT INTO region VALUES($$NORTHERN AFRICA$$,$$Africa$$);
INSERT INTO region VALUES($$BALTICS$$,$$Europe$$);
